export const ADICIONAR_UM = 'ADICIONAR_UM',
             GET_CLIENTES = 'GET_CLIENTES',
             ADD_CLIENTE = 'ADD_CLIENTE',
             UPDATE_CLIENTE = 'UPDATE_CLIENTE',
             DELETE_CLIENTE = 'DELETE_CLIENT',
             SET_ORDENACAO = 'SET_ORDENACAO',
             SET_PESQUISA = 'SET_PESQUISA',
             SET_CLIENTE =  'SET_CLIENTE'